[project]
name = "cs336-llms-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tokenizer>=3.5.3",
    "torch>=2.9.0",
]
